#------------------------------------------------------------
# Importing the datasets

library(ggplot2) 
library(readr)
library(dplyr)
library(data.table)
library(formattable)
library(base)
library(rworldmap)
library(wesanderson)
pal <- wes_palette("Zissou1", 100, type = "continuous")

#------------------------------------------------------------
# Working directory

getwd()
# setwd()

#----------------------------------------------------------------------------
# Read dataset

df<-read.csv('crashes_5600_1908_2009.csv')
print(head(df,4))

#----------------------------------------------------------------------------
# Viewing the data

df<-subset(df,select = -Summary)
print(colnames(df))
print(dim(df))
print(head(df,4))
str(df)

#----------------------------------------------------------------------------
# Map

crash <- df
temp <- crash
temp$loc_new <- crash$Location
temp$loc_new <- as.character(temp$loc_new)
temp$loc_new <- ifelse(temp$loc_new=='',NA,temp$loc_new)
temp <- na.omit(temp)
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bVenezuela\\b',loc_new),'Venezuela',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCanada\\b',loc_new),'Canada',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNetherlands\\b',loc_new),'Netherlands',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBrazil\\b',loc_new),'Brazil',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIndia\\b',loc_new),'India',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bChile\\b',loc_new),'Chile',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUganda\\b',loc_new),'Uganda',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bJapan\\b',loc_new),'Japan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFrance\\b',loc_new),'France',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bItaly\\b',loc_new),'Italy',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTanzania\\b',loc_new),'Tanzania',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEcuador\\b',loc_new),'Ecuador',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKyrgyzstan\\b',loc_new),'Kyrgyzstan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUnited Arab Emirates\\b',loc_new),'United Arab Emirates',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bRussia\\b',loc_new),'Russia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIndonesia\\b',loc_new),'Indonesia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSomalia\\b',loc_new),'Somalia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMexico\\b',loc_new),'Mexico',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGuatemala\\b',loc_new),'Guatemala',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bColombia\\b',loc_new),'Colombia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSudan\\b',loc_new),'Sudan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAustralia\\b',loc_new),'Australia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNigeria\\b',loc_new),'Nigeria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPanama\\b',loc_new),'Panama',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNepal\\b',loc_new),'Nepal',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPoland\\b',loc_new),'Poland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUkraine\\b',loc_new),'Ukraine',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDemocratiRepubliCongo\\b',loc_new),'DemocratiRepubliCongo',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bThailand\\b',loc_new),'Thailand',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEthiopia\\b',loc_new),'Ethiopia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPeru\\b',loc_new),'Peru',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMongolia\\b',loc_new),'Mongolia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCongo\\b',loc_new),'Congo',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNorway\\b',loc_new),'Norway',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGermany\\b',loc_new),'Germany',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPakistan\\b',loc_new),'Pakistan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIran\\b',loc_new),'Iran',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIraq\\b',loc_new),'Iraq',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAfghanistan\\b',loc_new),'Afghanistan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNapal\\b',loc_new),'Nepal',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBolivia\\b',loc_new),'Bolivia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHungary\\b',loc_new),'Hungary',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAzerbaijan\\b',loc_new),'Azerbaijan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAlbania\\b',loc_new),'Albania',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUnited Kingdom\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSaudi Arabia\\b',loc_new),'Saudi Arabia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bChina\\b',loc_new),'China',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPapua New Guinea\\b',loc_new),'Papua New Guinea',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGabon\\b',loc_new),'Gabon',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKenya\\b',loc_new),'Kenya',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKazakhstan\\b',loc_new),'Kazakhstan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEgypt\\b',loc_new),'Egypt',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNew Zealand\\b',loc_new),'New Zealand',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHaiti\\b',loc_new),'Haiti',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKenya\\b',loc_new),'Kenya',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBahamas\\b',loc_new),'Bahamas',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAlgeria\\b',loc_new),'Algeria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNamibia\\b',loc_new),'Namibia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTurkey\\b',loc_new),'Turkey',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEstonia\\b',loc_new),'Estonia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPhilippines\\b',loc_new),'Philippines',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bLuxembourg\\b',loc_new),'Luxembourg',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTaiwan\\b',loc_new),'Taiwan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCameroon\\b',loc_new),'Cameroon',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bChad\\b',loc_new),'Chad',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAngola\\b',loc_new),'Angola',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSwitzerland\\b',loc_new),'Switzerland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bRussian\\b',loc_new),'Russia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIvory Coast\\b',loc_new),'Ivory Coast',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGhana\\b',loc_new),'Ghana',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSwitzerland\\b',loc_new),'Switzerland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSpain\\b',loc_new),'Spain',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bArgentina\\b',loc_new),'Argentina',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bArmenia\\b',loc_new),'Armenia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBurma\\b',loc_new),'Myanmar',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMyanmar\\b',loc_new),'Myanmar',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPhilipines\\b',loc_new),'Philipines',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBelgium\\b',loc_new),'Belgium',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCalifornia\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTexas\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIowa\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNew York\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAlaska\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNevada\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWisconsin\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMinnesota\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWyoming\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMichigan\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCalifornia\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOhio\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bVermont\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPuerto Rico\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMontana\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bArizona\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHawaii\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWashington\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOregon\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIllinois\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDakota\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bLouisiana\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPennsylvania\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bColorado\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWake\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSouth Africa\\b',loc_new),'South Africa',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMalawi\\b',loc_new),'Malawi',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bLaos\\b',loc_new),'Laos',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAK\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNew Hampshire\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCarolina\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNew Jersey\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bVirginia\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bRhode Island\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIndiana\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGeorgia\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bManitoba\\b',loc_new),'Canada',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBulgaria\\b',loc_new),'Bulgaria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bVietnam\\b',loc_new),'Vietnam',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bConnecticut\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBritish Columbia\\b',loc_new),'Canada',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKentucky\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bKansas\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWisconson\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bArkansas\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUnited States\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMissouri\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTennessee\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUSSR\\b',loc_new),'Russia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUzbekistan\\b',loc_new),'Uzbekistan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNebraska\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTrinidad\\b',loc_new),'Trinidad',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEngland\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNewfoundland\\b',loc_new),'Canada',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPortugal\\b',loc_new),'Portugal',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMali\\b',loc_new),'Mali',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bChina\\b',loc_new),'China',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMassachusetts\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGreece\\b',loc_new),'Greece',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNicaragua\\b',loc_new),'Nicaragua',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAmerican\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUK\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSingapore\\b',loc_new),'Singapore',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMalaysia\\b',loc_new),'Malaysia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSenegal\\b',loc_new),'Senegal',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bYemen\\b',loc_new),'Yemen',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAlabama\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUtah\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIdaho\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCA\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCosta Rica\\b',loc_new),'Costa Rica',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bUruguay\\b',loc_new),'Uruguay',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMozambique\\b',loc_new),'Mozambique',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOman\\b',loc_new),'Oman',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bRomania\\b',loc_new),'Romania',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCosta Rica\\b',loc_new),'Costa Rica',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bZimbabwe\\b',loc_new),'Zimbabwe',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bU.S\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSyria\\b',loc_new),'Syria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMorocco\\b',loc_new),'Morocco',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIceland\\b',loc_new),'Iceland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMaine\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMorocco\\b',loc_new),'Morocco',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWashingon\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAmsterdam\\b',loc_new),'Netherlands',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAustria\\b',loc_new),'Austria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bVienna\\b',loc_new),'Austria',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bYugoslavia\\b',loc_new),'Yugoslavia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGreenland\\b',loc_new),'Greenland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMacedonia\\b',loc_new),'Macedonia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFrench Equitorial Africa\\b',loc_new),'French Equitorial Africa',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFiji\\b',loc_new),'Fiji',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCzechoslovakia\\b',loc_new),'Czechoslovakia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHonduras\\b',loc_new),'Honduras',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEl Salvador\\b',loc_new),'El Salvador',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDominican Republic\\b',loc_new),'Dominican Republic',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDenmark\\b',loc_new),'Denmark',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMississippi\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCambodia\\b',loc_new),'Cambodia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMaryland\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bScotland\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHati\\b',loc_new),'Haiti',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNew Guinea\\b',loc_new),'New Guinea',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMauritania\\b',loc_new),'Mauritania',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOklahoma\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTennesee\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCuba\\b',loc_new),'Cuba',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSouth Korea\\b',loc_new),'South Korea',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSweden\\b',loc_new),'Sweden',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFrench Polynesia\\b',loc_new),'French Polynesia:Tahaa',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bHong Kong\\b',loc_new),'China',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSri Lanka\\b',loc_new),'Sri Lanka',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bJamaica\\b',loc_new),'Jamaica',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSierre Leone\\b',loc_new),'Sierra Leone',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDeleware\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFrench West Africa\\b',loc_new),'French West Africa',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bNorth Korea\\b',loc_new),'North Korea',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIsrael\\b',loc_new),'Israel',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMassachusett\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bDelaware\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMalagasy Republic\\b',loc_new),'Malagasy Republic',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMalta\\b',loc_new),'Malta',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bFlorida\\b',loc_new),'USA',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIreland\\b',loc_new),'Ireland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEnglish\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOkinawa\\b',loc_new),'Japan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bMalaya\\b',loc_new),'Malaysia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bWest Indies\\b',loc_new),'West Indies',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bOkinawa\\b',loc_new),'Japan',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBahrain\\b',loc_new),'Bahrain',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bThiland\\b',loc_new),'Thailand',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bIrish\\b',loc_new),'Ireland',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bBelize\\b',loc_new),'Belize',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGuam\\b',loc_new),'Guam',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bEquatorial Guinea\\b',loc_new),'Equatorial Guinea',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSierra Leone\\b',loc_new),'Sierra Leone',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bTunisia\\b',loc_new),'Tunisia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bLithuania\\b',loc_new),'Lithuania',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bSamoa\\b',loc_new),'Samoa',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bAzores\\b',loc_new),'Azores:Sao Miguel',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bCanary Islands\\b',loc_new),'Spain',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGuadeloupe\\b',loc_new),'Guadeloupe',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bGibraltar\\b',loc_new),'UK',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bZambia\\b',loc_new),'Zambia',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bChad\\b',loc_new),'Chad',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bRwanda\\b',loc_new),'Rwanda',loc_new))
temp <- temp %>% mutate(loc_new=ifelse(grepl('\\bPoland\\b',loc_new),'Poland',loc_new))
temp <- temp %>% group_by(loc_new) %>% summarise(n=n())
temp <- temp %>% arrange(desc(n))

spdf <- joinCountryData2Map(temp, joinCode="NAME", nameJoinColumn="loc_new")

mapCountryData(spdf, nameColumnToPlot="n", catMethod="logFixedWidth")

